export const menuData = [
  {
    title: "Gold chain",
    subItems: [
      {
        title: "NEW JEWELRY",
        items: [
          "Silver chain",
          "All New Jewelry",
          "Disney x GK Jeweler",
          "Flower Jewelry",
          "Lunar New Year",
          "GK Jeweler Moments",
          "GK Jeweler Timeless",
          "Lab-Grown Diamonds",
          "GK Jeweler ME",
        ],
      },
      {
        title: "TRENDING NOW",
        items: [
          "All Jewelry",
          "Bestsellers",
          "Tennis Bracelets",
          "Hearts & Promise Rings",
          "Engravable Jewelry",
          "Charm Necklaces",
          "Create a Custom Charm Bracelet",
          "Lab Grown Diamonds",
          "The Gold Edit",
          "Matching Sets",
          "For Him",
        ],
      },
      {
        title: "OFFERS & PROMOTIONS",
        items: ["All Offers & Promotions", "Last Chance | Up to 70% Off"],
      },
    ],
  },
  {
    title: "gold bracelets",
    subItems: [
      {
        title: "NEW JEWELRY",
        items: [
          "Silver bracelets",
          "diamond bracelets",
          "All New Jewelry",
          "Disney x GK Jeweler",
          "Flower Jewelry",
          "Lunar New Year",
          "GK Jeweler Moments",
          "GK Jeweler Timeless",
          "Lab-Grown Diamonds",
          "GK Jeweler ME",
        ],
      },
      {
        title: "GIFTS",
        items: [
          "Gift Sets",
          "Best Gifts for Her",
          "Best Gifts for Him",
          "Gifts Under ₹5,000",
          "Gifts Under ₹10,000",
          "Personalized Gifts",
          "Anniversary Gifts",
          "Birthday Gifts",
          "Wedding & Bridal Gifts",
        ],
      },
      {
        title: "COLLECTIONS",
        items: [
          "Disney Collection",
          "Harry Potter Collection",
          "Marvel Collection",
          "Star Wars Collection",
          "Nature-Inspired Jewelry",
          "Celestial Collection",
          "Vintage-Inspired Jewelry",
        ],
      },
    ],
  },
  {
    title: " gold earrings",
    subItems: [
      {
        title: "NEW JEWELRY",
        items: [
          "Silver earrings",
          "diamond earrings",
          "All New Jewelry",
          "Disney x GK Jeweler",
          "Flower Jewelry",
          "Lunar New Year",
          "GK Jeweler Moments",
          "GK Jeweler Timeless",
          "Lab-Grown Diamonds",
          "GK Jeweler ME",
        ],
      },
      {
        title: "BY MATERIAL",
        items: [
          "Gold Jewelry",
          "Silver Jewelry",
          "Rose Gold Jewelry",
          "Platinum Jewelry",
          "Diamond Jewelry",
          "Pearl Jewelry",
          "Gemstone Jewelry",
        ],
      },
      {
        title: "BY OCCASION",
        items: [
          "Everyday Wear",
          "Office Wear",
          "Party Wear",
          "Casual Wear",
          "Traditional Wear",
          "Festive Wear",
        ],
      },
    ],
  },
  {
    title: "gold ring",
    subItems: [
      {
        title: "NEW JEWELRY",
        items: [
          "Silver ring",
          "All New Jewelry",
          "Disney x GK Jeweler",
          "Flower Jewelry",
          "Lunar New Year",
          "GK Jeweler Moments",
          "GK Jeweler Timeless",
          "Lab-Grown Diamonds",
          "GK Jeweler ME",
        ],
      },
      {
        title: "BY MATERIAL",
        items: [
          "Gold Jewelry",
          "Silver Jewelry",
          "Rose Gold Jewelry",
          "Platinum Jewelry",
          "Diamond Jewelry",
          "Pearl Jewelry",
          "Gemstone Jewelry",
        ],
      },
      {
        title: "BY OCCASION",
        items: [
          "Everyday Wear",
          "Office Wear",
          "Party Wear",
          "Casual Wear",
          "Traditional Wear",
          "Festive Wear",
        ],
      },
    ],
  },
  {
    title: "gold Anklet",
    subItems: [
      {
        title: "NEW JEWELRY",
        items: [
          "Silver Anklet",
          "All New Jewelry",
          "Disney x GK Jeweler",
          "Flower Jewelry",
          "Lunar New Year",
          "GK Jeweler Moments",
          "GK Jeweler Timeless",
          "Lab-Grown Diamonds",
          "GK Jeweler ME",
        ],
      },
      {
        title: "BY MATERIAL",
        items: [
          "Gold Jewelry",
          "Silver Jewelry",
          "Rose Gold Jewelry",
          "Platinum Jewelry",
          "Diamond Jewelry",
          "Pearl Jewelry",
          "Gemstone Jewelry",
        ],
      },
      {
        title: "BY OCCASION",
        items: [
          "Everyday Wear",
          "Office Wear",
          "Party Wear",
          "Casual Wear",
          "Traditional Wear",
          "Festive Wear",
        ],
      },
    ],
  },
  {
    title: "nose ring",
    subItems: [
      {
        title: "NEW JEWELRY",
        items: [
          "Silver ring",
          "Diamond ring",
          "All New Jewelry",
          "Disney x GK Jeweler",
          "Flower Jewelry",
          "Lunar New Year",
          "GK Jeweler Moments",
          "GK Jeweler Timeless",
          "Lab-Grown Diamonds",
          "GK Jeweler ME",
        ],
      },
      {
        title: "BY MATERIAL",
        items: [
          "Gold Jewelry",
          "Silver Jewelry",
          "Rose Gold Jewelry",
          "Platinum Jewelry",
          "Diamond Jewelry",
          "Pearl Jewelry",
          "Gemstone Jewelry",
        ],
      },
      {
        title: "BY OCCASION",
        items: [
          "Everyday Wear",
          "Office Wear",
          "Party Wear",
          "Casual Wear",
          "Traditional Wear",
          "Festive Wear",
        ],
      },
    ],
  },
  {
    title: "Collections",
    subItems: [
      {
        title: "BY MATERIAL",
        items: [
          "Gold Jewelry",
          "Silver Jewelry",
          "Watches Versace",
          "versus",
          "phippline",
          "Rolex pre-owned",
          "Rose Gold Jewelry",
          "Platinum Jewelry",
          "Diamond Jewelry",
          "Pearl Jewelry",
          "Gemstone Jewelry",
        ],
      },
    ],
  },
];
export const sections = [
  {
    title: "Shop",
    links: [
      "Promotion & Offers",
      "Charms",
      "Bracelets",
      "Rings",
      "Necklaces & Pendants",
      "Earrings",
      "Lab-Grown Diamonds",
      "GK Jeweler Collections",
      "Gifts",
      "Gift Cards",
    ],
  },
  {
    title: "Customer Service",
    links: [
      "FAQs",
      "Orders",
      "Shipping",
      "Returns",
      "Size Guide",
      "Product Care",
      "GK Jeweler Cares",
      "Warranty",
      "Contact Us",
    ],
  },
  {
    title: "Services",
    links: ["Klarna", "Afterpay", "GK Jeweler Credit Card"],
  },
  {
    title: "Manage",
    links: [
      "My GK Jeweler",
      "My Account",
      "My Details",
      "My Orders",
      "Wish List",
    ],
  },
  {
    title: "About Us",
    links: [
      "About GK Jeweler",
      "GK Jeweler Company",
      "Store Locator",
      "Authorized GK Jeweler Online Retailers",
      "Careers",
      "Terms & Conditions",
      "Privacy Policy",
      "Cookie Policy",
      "Site Map",
    ],
  },
];
